

// speakers
const CREATE_SPEAKER = 'CREATE_SPEAKER';
const CREATE_SPEAKER_FAILURE = 'CREATE_SPEAKER_FAILURE';
const CREATE_SPEAKER_SUCCESS = 'CREATE_SPEAKER_SUCCESS';
const DELETE_SPEAKER = 'DELETE_SPEAKER';
const DELETE_SPEAKER_FAILURE = 'DELETE_SPEAKER_FAILURE';
const DELETE_SPEAKER_SUCCESS = 'DELETE_SPEAKER_SUCCESS';
const FETCH_SPEAKER = 'FETCH_SPEAKER';
const FETCH_SPEAKER_FAILURE = 'FETCH_SPEAKER_FAILURE';
const FETCH_SPEAKER_SUCCESS = 'FETCH_SPEAKER_SUCCESS';
const FETCH_SPEAKERS = 'FETCH_SPEAKERS';
const FETCH_SPEAKERS_FAILURE = 'FETCH_SPEAKERS_FAILURE';
const FETCH_SPEAKERS_SUCCESS = 'FETCH_SPEAKERS_SUCCESS';
const UPDATE_SPEAKER = 'UPDATE_SPEAKER';
const UPDATE_SPEAKER_FAILURE = 'UPDATE_SPEAKER_FAILURE';
const UPDATE_SPEAKER_SUCCESS = 'UPDATE_SPEAKER_SUCCESS';
const UPLOAD_SPEAKER_PHOTO = 'UPLOAD_SPEAKER_PHOTO';
const UPLOAD_SPEAKER_PHOTO_FAILURE = 'UPLOAD_SPEAKER_PHOTO_FAILURE';
const UPLOAD_SPEAKER_PHOTO_SUCCESS = 'UPLOAD_SPEAKER_PHOTO_SUCCESS';

