const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
const CREATE_ORGANIZATION_FAILURE = 'CREATE_ORGANIZATION_FAILURE';
const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';
const DELETE_ORGANIZATION_FAILURE = 'DELETE_ORGANIZATION_FAILURE';
const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';
const FETCH_ORGANIZATION = 'FETCH_ORGANIZATION';
const FETCH_ORGANIZATION_FAILURE = 'FETCH_ORGANIZATION_FAILURE';
const FETCH_ORGANIZATION_SUCCESS = 'FETCH_ORGANIZATION_SUCCESS';
const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
const FETCH_ORGANIZATIONS_FAILURE = 'FETCH_ORGANIZATIONS_FAILURE';
const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
const UPDATE_ORGANIZATION_FAILURE = 'UPDATE_ORGANIZATION_FAILURE';
const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS';
const UPLOAD_ORGANIZATION_LOGO = 'UPLOAD_ORGANIZATION_LOGO';
const UPLOAD_ORGANIZATION_LOGO_FAILURE = 'UPLOAD_ORGANIZATION_LOGO_FAILURE';
const UPLOAD_ORGANIZATION_LOGO_SUCCESS = 'UPLOAD_ORGANIZATION_LOGO_SUCCESS';



